name: pcds-ci-helpers

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  standard:
    uses: pcdshub/pcds-ci-helpers/.github/workflows/pre-commit.yml@master
    with:
      args: "--all-files --show-diff-on-failure"
      annotate: true
